---
name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: generate-matrix
        uses: wandnz/action-supported-distro-releases@v1

  molecule:
    name: Molecule (ansible:${{ matrix.ansible }}, ${{ matrix.target }})
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        target: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
        ansible:
          - "2.10"
          - "latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Setup ansible
        run: |
          if [[ "${{ matrix.ansible }}" == "latest" ]]; then
            pip3 install ansible
          else
            pip3 install ansible~=${{ matrix.ansible }}
          fi
      - name: Setup ansible problem matchers
        uses: wandansible/action-ansible-problem-matchers@v1
      - name: Install test dependencies
        run: pip3 install -r test-requirements.txt
      - name: Run molecule
        run: molecule test
        env:
          MOLECULE_DOCKER_IMAGE: ${{ matrix.target }}
